/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmissionRouteImport } from './routes/api/submission'
import { Route as ApiSubmissionShortIdRouteImport } from './routes/api/submission.$shortId'
import { Route as ApiSubmissionEmailShortIdRouteImport } from './routes/api/submission/email.$shortId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionRoute = ApiSubmissionRouteImport.update({
  id: '/api/submission',
  path: '/api/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionShortIdRoute = ApiSubmissionShortIdRouteImport.update({
  id: '/$shortId',
  path: '/$shortId',
  getParentRoute: () => ApiSubmissionRoute,
} as any)
const ApiSubmissionEmailShortIdRoute =
  ApiSubmissionEmailShortIdRouteImport.update({
    id: '/email/$shortId',
    path: '/email/$shortId',
    getParentRoute: () => ApiSubmissionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/submission': typeof ApiSubmissionRouteWithChildren
  '/api/submission/$shortId': typeof ApiSubmissionShortIdRoute
  '/api/submission/email/$shortId': typeof ApiSubmissionEmailShortIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/submission': typeof ApiSubmissionRouteWithChildren
  '/api/submission/$shortId': typeof ApiSubmissionShortIdRoute
  '/api/submission/email/$shortId': typeof ApiSubmissionEmailShortIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/submission': typeof ApiSubmissionRouteWithChildren
  '/api/submission/$shortId': typeof ApiSubmissionShortIdRoute
  '/api/submission/email/$shortId': typeof ApiSubmissionEmailShortIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/submission'
    | '/api/submission/$shortId'
    | '/api/submission/email/$shortId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/submission'
    | '/api/submission/$shortId'
    | '/api/submission/email/$shortId'
  id:
    | '__root__'
    | '/'
    | '/api/submission'
    | '/api/submission/$shortId'
    | '/api/submission/email/$shortId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSubmissionRoute: typeof ApiSubmissionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submission': {
      id: '/api/submission'
      path: '/api/submission'
      fullPath: '/api/submission'
      preLoaderRoute: typeof ApiSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submission/$shortId': {
      id: '/api/submission/$shortId'
      path: '/$shortId'
      fullPath: '/api/submission/$shortId'
      preLoaderRoute: typeof ApiSubmissionShortIdRouteImport
      parentRoute: typeof ApiSubmissionRoute
    }
    '/api/submission/email/$shortId': {
      id: '/api/submission/email/$shortId'
      path: '/email/$shortId'
      fullPath: '/api/submission/email/$shortId'
      preLoaderRoute: typeof ApiSubmissionEmailShortIdRouteImport
      parentRoute: typeof ApiSubmissionRoute
    }
  }
}

interface ApiSubmissionRouteChildren {
  ApiSubmissionShortIdRoute: typeof ApiSubmissionShortIdRoute
  ApiSubmissionEmailShortIdRoute: typeof ApiSubmissionEmailShortIdRoute
}

const ApiSubmissionRouteChildren: ApiSubmissionRouteChildren = {
  ApiSubmissionShortIdRoute: ApiSubmissionShortIdRoute,
  ApiSubmissionEmailShortIdRoute: ApiSubmissionEmailShortIdRoute,
}

const ApiSubmissionRouteWithChildren = ApiSubmissionRoute._addFileChildren(
  ApiSubmissionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSubmissionRoute: ApiSubmissionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
